### ISSUE TITLE
How you could have come up with Paxos yourself: small issue with modified messages changes

### ISSUE THREAD

**Issue by nginth** [yshui/explain-algorithms#2]
I'm not familiar with Paxos, so forgive me if this is incorrect. 

According to the article, the algorithm that you built from scratch has `x` in the Proposal and TenativeVote messages, so the first two lines of messages should be:

```
$\sc{PROPOSAL}(\#attempt, client_i, x)$ => $\sc{PREPARE}(\#attempt, client_i)$
$\sc{TENTATIVE}\sc{VOTE}(\#attempt, coord_i, x)$ => $\sc{PROMISE}(\#attempt, coord_i)$
```

Great article by the way!

**Comment by yshui** [comment]
@nginth Thanks!

The `x` was removed in the "Back to Paxos" section, that's why I didn't include in the message mapping.
